---
title: "Medical Gene Benchmark Inclusion and Overlap"
date: '`r Sys.Date()`'
output: 
    bookdown::html_document2:
        toc: true
        toc_float: true
        df_print: paged
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
```

## Loading and Tidying
# Loading and Tidying Data
```{r}
## Gene source and testing modality information
mrg_info_tbl <- here("data","tidy","gene_list_info.tsv") %>% 
    read_tsv(col_types = "cccddcccllddddddd")

## Gene Stratfication Overlap
gene_strat_df <- read_tsv(here("data","tidy","gene_strat_overlap.tsv"))

## TODO - replace with new updated coverage data
## Benchmark and Asm Coverage information 
bench_asm_cov_df <- here("data","tidy","gene_asm_bench_coverage.tsv") %>% 
    read_tsv(col_types = "ccclccddd")
```

Combining Benchmark Coverage and Strat data frames
```{r}
mrg_gene_cats <- bench_asm_cov_df %>% 
    filter(str_detect(coords, "[MTXY]",negate = TRUE),
           ref == "GRCh38",
           region == "gene") %>% 
    select(-vars, -svs) %>% 
    pivot_wider(names_from = benchmark, values_from = cov) %>% 
    mutate(gene_cat = case_when(in_mrg ~ "MRG",
                                v4 > 0.9 ~ "V4",
                                v4 < 0.9 & hifi < 1 ~ "Not Benchmarked",
                                mrg == 0 & hifi == 1 ~ "Excluded?",
                                TRUE ~ "???"))

bench_cov_anno_df <- mrg_gene_cats %>% 
    left_join(gene_strat_df)
```

## Panels

### V4 Coverage

```{r}
v4_cov_df <- bench_asm_cov_df %>% 
    ## Excluding mito and sex chromosomes
    filter(ref == "GRCh38",
           str_detect(coords, "[MTXY]",negate = TRUE), 
           region == "gene") %>% 
     pivot_wider(id_cols = c("gene","ref","coords"), 
                 names_from = benchmark, values_from = cov)

n_cov_df <- v4_cov_df %>% 
    mutate(cov_lvl = if_else(v4 > 0.9, "high v4 cov", "low v4 cov")) %>% 
    count(ref, cov_lvl)

v4_low_cov_df <- bench_asm_cov_df %>% 
    ## Excluding mito and sex chromosomes
    filter(ref == "GRCh38",
           str_detect(coords, "[MTXY]",negate = TRUE), 
           region == "gene") %>% 
     pivot_wider(id_cols = c("gene","ref","coords"), 
                 names_from = benchmark, values_from = cov) %>% 
    filter(v4 < 0.9) %>% 
    mutate(benchmarked = if_else(mrg > 0, "in MRG","not in MRG"))
```

```{r}
n_high_v4_cov <- n_cov_df$n[n_cov_df$cov_lvl == "high v4 cov"]
n_low_v4_cov <- n_cov_df$n[n_cov_df$cov_lvl == "low v4 cov"]

(
    v4_cov_plt <- ggplot(v4_low_cov_df) +
        geom_histogram(
            aes(x = v4, fill = benchmarked),
            color = "grey20",
            size = 0.25,
            bins = 90
        ) +
        geom_text(aes(
            x = 0.05,
            y = 42,
            label = str_c(n_high_v4_cov,
                          " High Coverage Genes (not shown)"),
            hjust = 0
        )) +
        geom_text(aes(
            x = 0.05,
            y = 38,
            label = str_c(n_low_v4_cov, 
                          " Low Coverage Genes"),
            hjust = 0
        )) +
        theme_bw() +
        labs(x = "Gene Coverage by V4 Benchmark", y = "Number of Genes") +
        theme(legend.position = "bottom",
              legend.title = element_blank())
)
```


### MRG Gene Coverage

```{r}
mrg_gene_cov <- bench_cov_anno_df %>% 
    filter(gene_cat == "MRG") %>% 
    select(gene, ref, coords) %>% 
    distinct() %>% 
    left_join(bench_asm_cov_df) %>% 
    filter(ref == "GRCh38", 
           str_detect(coords, "[MTXY]",negate = TRUE),
           benchmark == "mrg")

(mrg_gene_cov_plt <- ggplot(mrg_gene_cov) + 
    geom_histogram(aes(x = cov, fill = region), 
                   position = "dodge",
                   color = "grey40",
                   size = 0.25, bins = 50) + 
    theme_bw() +
    labs(x = "Benchmark Coverage", y = "Number of Genes", fill = "") +
    theme(legend.position = c(0.15,0.9), 
          legend.direction = "horizontal", legend.background = element_blank()))
```

### MRG v. V4 Coverage (TO REPLACE V4 and MRG Coverage)

### Difficult Gene Overlap
```{r}
(diff_overlap_plt <- bench_cov_anno_df %>% 
    filter(ref == "GRCh38",
           gene_cat %in% c("V4", "MRG","Not Benchmarked"),
        str_detect(coords, "[MTXY]",negate = TRUE),
        strat == "allDiff") %>% 
    mutate(gene_cat = factor(gene_cat, 
                             level = c("V4", "MRG","Not Benchmarked"),
                             labels = c(">90% coverage by V4.2.1",
                                        "in MRG Benchmark",
                                        "Not Benchmarked"))
           ) %>% 
    ggplot() + 
    geom_histogram(aes(x = overlap, fill = gene_cat), 
                   color = "grey40", size = 0.25, bins = 100) + 
    facet_wrap(~gene_cat, ncol = 1, scales = "free_y") + 
    theme_bw() + 
    theme(legend.position = "none") + 
    labs(x = "Fraction of gene with challenging sequence or variants", 
         y = "Number of Genes",
         fill = "Benchmark"))
```

### Small Variant Size Distribution

### Large Variant Size Distribution 










# Session Information
## System Information
```{r}
sessioninfo::platform_info()
```


## Package Versions
```{r}
sessioninfo::package_info() %>% 
    filter(attached = TRUE) %>% 
    select(package, loadedversion, date, source) %>%
    knitr::kable(booktabs = TRUE, row.names = FALSE)
```